#!/bin/bash
xgettext --language=Python --keyword=_ --output=po/garfio.pot usr/lib/tuquito/garfio/garfio.py --from-code=utf-8
xgettext --language=Shell --output=po/garfio.pot usr/bin/garfio --from-code=utf-8 -j
