#!/bin/sh
# postinst script for Garfio
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
	if [ -x /usr/bin/update-mime-database ]; then
		/usr/bin/update-mime-database /usr/share/mime
	fi
	if [ -x /usr/bin/update-desktop-database ]; then
		/usr/bin/update-desktop-database
	fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "argumentos '$1'" >&2
        exit 1
    ;;
esac

exit 0

